<?php
/*
@author:Miguel Anagel Porras Najera
El siguiente script son los Querys que se utilizan en el programa de Reportes_Polizas_Impuesto
*/

/***************************************************************************CONSULTAS*************************************************************************************/
$QUERY_CONSULTA_OPERACIONES_DIA_CAAAREM3="SELECT A.REFERENCE_NO REFERENCE, A.PEDIMENTO_REFERENCE_NO REFERENCE_NO,A.PEDIMENTO_NO PEDIMENTO, (CASE WHEN B.OPERATION_TYPE='1' THEN 'IMP' ELSE 'EXP' END)
TIPO_OPERACION, B.DOC_CD CLAVE_PEDIMENTO, B.REGIME_CD REGIMEN, (SELECT DATES FROM REG_AMEND_GENDATE WHERE REFERENCE_NO = A.REFERENCE_NO AND DATE_CD = 2) FECHA_PAGO, B.EXCHANGE_RATE_CD TIPO_CAMBIO, B.GROSS_WEIGHT PESO_BRUTO, B.ENTRANCE_EXIT TRNENTSAL, CASE WHEN G.APELLIDO_PATERNO = '' || isnull(G.APELLIDO_PATERNO) THEN G.CORPORATE_NAME ELSE CONCAT(CONCAT(CONCAT(CONCAT(G.CORPORATE_NAME,' ') , G.APELLIDO_PATERNO),' '),G.APELLIDO_MATERNO )  END IMPORTADOR_EXPORTADOR, G.RFC  RFC, A.USER_ID  USUARIO, K.BANK_NAME BANCO, A.BFIRMA  PAGADO_BANCO, B.PRICE_PAID PRECIO_PAGADO_ME, B.DOLLER_VALUE VALOR_DOLARES, MYROUND(B.INSURANCE*B.INSURANCE_EXCHANGE*B.EXCHANGE_RATE_CD)
SEGUROS,MYROUND(B.FREIGHTS  *B.FREIGHTS_EXCHANGE* B.EXCHANGE_RATE_CD) FLETES ,
MYROUND(B.PACKAGES*B.PACKAGES_EXCHANGE*B.EXCHANGE_RATE_CD) EMBALAJES,MYROUND(B.OTHER_INCRMENTABLES*B.OTHER_INCRM_EXCHANGE*B.EXCHANGE_RATE_CD)
OTHER_INCRMENTABLES,B.ELECTRONIC_SIGN ACUSE, A.CLAVE_PREVALIDADOR CVE_PREVALIDADOR, (SELECT SUM(TOTAL_AMT)
 FROM REG_AMEND_PED_PAYMENT WHERE CONTRIBUTIONS_CD = 1 AND FORM_PAYMENT = 0 AND REFERENCE_NO = A.REFERENCE_NO ) DTA_EFECTIVO, (SELECT SUM(TOTAL_AMT)
 FROM REG_AMEND_PED_PAYMENT WHERE CONTRIBUTIONS_CD = 15 AND FORM_PAYMENT = 0 AND REFERENCE_NO = A.REFERENCE_NO )
 PREV_EFECTIVO, (SELECT SUM(TOTAL_AMT)
  FROM REG_AMEND_PED_PAYMENT WHERE CONTRIBUTIONS_CD = 7 AND FORM_PAYMENT = 0 AND REFERENCE_NO = A.REFERENCE_NO ) RECARGOS_EFECTIVO, (SELECT SUM(TOTAL_AMT)
  FROM REG_AMEND_PED_PAYMENT WHERE CONTRIBUTIONS_CD = 11 AND FORM_PAYMENT = 0 AND REFERENCE_NO = A.REFERENCE_NO ) MULTAS_EFECTIVO, (SELECT SUM(TOTAL_AMT)
  FROM REG_AMEND_PED_PAYMENT WHERE CONTRIBUTIONS_CD = 18 AND FORM_PAYMENT = 0 AND REFERENCE_NO = A.REFERENCE_NO ) ECI_EFECTIVO,  (SELECT MYROUND(SUM(S.TOTAL_PAYMENT) FINIGI)
  FROM REG_ITEM_CONT_PAYMENT S  WHERE S.CONTRIBUTION_CD = 6 AND S.PAYMENT_FORM = 0  AND S.REFERENCE_NO = A.REFERENCE_NO ) IGI_EFECTIVO
  FROM PEDIMENTO_CAPTURE A
    LEFT JOIN AMD_COMP_AMENDMENT H ON (A.REFERENCE_NO=H.REFERENCE_NO)
    LEFT JOIN PEDIMENTO_CAPTURE P ON (A.REFERENCE_NO=P.REFERENCE_NO)
    LEFT JOIN REG_AMEND_PED_PAYMENT Y ON (A.REFERENCE_NO=Y.REFERENCE_NO)
    LEFT JOIN CAT_BANK K ON (A.BBANCO = K.BANK_CODE)
    LEFT JOIN REG_AMEND_GENDATA B ON (A.REFERENCE_NO = B.REFERENCE_NO)
    LEFT JOIN REG_AMEND_GENDATE  F ON ( A.REFERENCE_NO = F.REFERENCE_NO AND F.DATE_CD = 2)
    LEFT JOIN CAT_IMP_EXP   G ON ( B.CUSTOMER_CD=G.IMP_EXP_CD)
     WHERE A.LICENSE_NO='3151' AND A.CUSTOM_CD='47'  AND (DATE_FORMAT(H.DATE_PAYMENT, '%Y%m%d') >= '".$fechaQUERY."'  AND DATE_FORMAT(H.DATE_PAYMENT, '%Y%m%d')<= '".$fechaQUERY."' AND A.PEDIMENTO_TYPE=11
      OR DATE_FORMAT(F.DATES, '%Y%m%d') >= '".$fechaQUERY."'  AND DATE_FORMAT(F.DATES, '%Y%m%d')<= '".$fechaQUERY."' AND A.PEDIMENTO_TYPE=10 )  AND (A.PATENTE_IMPORTADA='3151' OR A.PATENTE_IMPORTADA=''
       OR A.PATENTE_IMPORTADA IS NULL)  GROUP BY A.PEDIMENTO_REFERENCE_NO  ORDER BY A.PEDIMENTO_TYPE,A.PEDIMENTO_REFERENCE_NO";
/***************************************************************************INSERTS**************************************************************************************/
/***************************************************************************UPDATES*************************************************************************************/
?>
